[package]
name = "polyepoxide-rocks"
version = "0.1.0"
edition = "2024"

[dependencies]
polyepoxide-core = { path = "../polyepoxide-core" }
rocksdb = "0.23"
thiserror = "2.0.17"

[dev-dependencies]
tempfile = "3"
